In [79]:
import numpy as np
from scipy.linalg import lu

np.set_printoptions(precision=3)

## A

In [80]:
def square_zeros(n):
    return np.array([[0 for _ in range(n)] for _ in range(n)])


A = square_zeros(3)
A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [81]:
A[0, 2] = 1
A

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [82]:
def rectangular_zeros(m, n):
    return np.array([[0 for _ in range(n)] for _ in range(m)])


rectangular_zeros(2, 3)

array([[0, 0, 0],
       [0, 0, 0]])

In [83]:
def identity_matrix(n):
    return np.array([[1 if i == j else 0 for j in range(n)] for i in range(n)])


identity_matrix(3)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [84]:
def E(n):
    return np.array([[(i+j+2)/((i+1)*(j+1)) for j in range(n)] for i in range(n)])


E(3)

array([[2.   , 1.5  , 1.333],
       [1.5  , 1.   , 0.833],
       [1.333, 0.833, 0.667]])

In [85]:
def matrices_equal(A, B):
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        return False
    for i in range(len(A)):
        for j in range(len(A[0])):
            if A[i][j] != B[i][j]:
                return False
    return True


matrices_equal(np.array([[1, 2], [1, 2]]), np.array([[1, 2], [1, 2]]))

True

In [86]:
def T(A):
    return np.array([[A[j][i] for j in range(len(A))] for i in range(len(A[0]))])


T([[1, 2, 3], [4, 5, 6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [87]:
def add(A, B):
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        raise ValueError("Matrices must have the same dimensions to be added")
    return np.array([[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))])


add(np.array([[1, 2, 3], [4, 5, 6]]), np.array([[1, 2, 3], [4, 5, 6]]))

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [88]:
def multiply_by_scalar(A, c):
    return np.array([[c * A[i][j] for j in range(len(A[0]))] for i in range(len(A))])


multiply_by_scalar(np.array([[1, 2, 3], [4, 5, 6]]), 3)

array([[ 3,  6,  9],
       [12, 15, 18]])

In [89]:
def multiply(A, B):
    if len(A[0]) != len(B):
        raise ValueError(
            "Number of columns in first matrix must be equal to number of rows in second matrix")
    result = [[0 for _ in range(len(B[0]))]
              for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return np.array(result)


multiply(np.eye(3), E(3))

array([[2.   , 1.5  , 1.333],
       [1.5  , 1.   , 0.833],
       [1.333, 0.833, 0.667]])

In [90]:
def is_inverse(A,  B):
    return matrices_equal(multiply(A, B), identity_matrix(A.shape[0]))


is_inverse(np.array([[1, 2], [2, 1]]),
           np.linalg.inv(np.array([[1, 2], [2, 1]])))

True

## B

In [91]:
def D(n):
    M = np.zeros((n, n))
    for i in range(n):
        M[i, i] = 2
        if i > 0:
            M[i, i-1] = -1
        if i < n-1:
            M[i, i+1] = -1
    return M


%time D(5)

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 2., -1.,  0.,  0.,  0.],
       [-1.,  2., -1.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.],
       [ 0.,  0., -1.,  2., -1.],
       [ 0.,  0.,  0., -1.,  2.]])

In [92]:
%time D(100)

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 2., -1.,  0., ...,  0.,  0.,  0.],
       [-1.,  2., -1., ...,  0.,  0.,  0.],
       [ 0., -1.,  2., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  2., -1.,  0.],
       [ 0.,  0.,  0., ..., -1.,  2., -1.],
       [ 0.,  0.,  0., ...,  0., -1.,  2.]])

In [93]:
%time D(1000)

CPU times: total: 0 ns
Wall time: 1.34 ms


array([[ 2., -1.,  0., ...,  0.,  0.,  0.],
       [-1.,  2., -1., ...,  0.,  0.,  0.],
       [ 0., -1.,  2., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  2., -1.,  0.],
       [ 0.,  0.,  0., ..., -1.,  2., -1.],
       [ 0.,  0.,  0., ...,  0., -1.,  2.]])

In [94]:
def matrix_minors(M):
    row = M.shape[0]
    col = M.shape[1]
    minors = np.zeros(M.shape)

    for i in range(row):
        for j in range(col):
            sub_matrix = np.delete(np.delete(M, i, axis=0), j, axis=1)
            minors[i, j] = np.linalg.det(sub_matrix)

    return minors


matrix_minors(D(5))

array([[ 5., -4.,  3., -2.,  1.],
       [-4.,  8., -6.,  4., -2.],
       [ 3., -6.,  9., -6.,  3.],
       [-2.,  4., -6.,  8., -4.],
       [ 1., -2.,  3., -4.,  5.]])

In [95]:
def D_new(n):
    return np.diag(np.full(n, 2)) + \
        np.diag(np.full(n-1, -1), 1) +\
        np.diag(np.full(n-1, -1), -1)


%time D_new(10000)

CPU times: total: 734 ms
Wall time: 1.62 s


array([[ 2, -1,  0, ...,  0,  0,  0],
       [-1,  2, -1, ...,  0,  0,  0],
       [ 0, -1,  2, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  2, -1,  0],
       [ 0,  0,  0, ..., -1,  2, -1],
       [ 0,  0,  0, ...,  0, -1,  2]])

In [96]:
%time D(10000)

CPU times: total: 0 ns
Wall time: 22.3 ms


array([[ 2., -1.,  0., ...,  0.,  0.,  0.],
       [-1.,  2., -1., ...,  0.,  0.,  0.],
       [ 0., -1.,  2., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  2., -1.,  0.],
       [ 0.,  0.,  0., ..., -1.,  2., -1.],
       [ 0.,  0.,  0., ...,  0., -1.,  2.]])

The new method is worse, because it needs to generate three matrices, and add them, whose complexity will be $\mathcal{O}(2n^2)$. However, the complexity of the first one is just $\mathcal{O}(3n)$.

In [97]:
L_cholesky = np.linalg.cholesky(D(5))

L_cholesky, L_cholesky.T

(array([[ 1.414,  0.   ,  0.   ,  0.   ,  0.   ],
        [-0.707,  1.225,  0.   ,  0.   ,  0.   ],
        [ 0.   , -0.816,  1.155,  0.   ,  0.   ],
        [ 0.   ,  0.   , -0.866,  1.118,  0.   ],
        [ 0.   ,  0.   ,  0.   , -0.894,  1.095]]),
 array([[ 1.414, -0.707,  0.   ,  0.   ,  0.   ],
        [ 0.   ,  1.225, -0.816,  0.   ,  0.   ],
        [ 0.   ,  0.   ,  1.155, -0.866,  0.   ],
        [ 0.   ,  0.   ,  0.   ,  1.118, -0.894],
        [ 0.   ,  0.   ,  0.   ,  0.   ,  1.095]]))

In [98]:
size = 100

DD = D(size)

In [99]:
np.linalg.cond(DD)

np.float64(4133.642926801001)

In [100]:
np.linalg.det(DD)

np.float64(101.00000000000146)

In [101]:
np.linalg.inv(DD)

array([[0.99 , 0.98 , 0.97 , ..., 0.03 , 0.02 , 0.01 ],
       [0.98 , 1.96 , 1.941, ..., 0.059, 0.04 , 0.02 ],
       [0.97 , 1.941, 2.911, ..., 0.089, 0.059, 0.03 ],
       ...,
       [0.03 , 0.059, 0.089, ..., 2.911, 1.941, 0.97 ],
       [0.02 , 0.04 , 0.059, ..., 1.941, 1.96 , 0.98 ],
       [0.01 , 0.02 , 0.03 , ..., 0.97 , 0.98 , 0.99 ]])

In [102]:
P = np.matmul(DD, np.linalg.inv(DD))
P

array([[ 1.000e+00,  0.000e+00,  0.000e+00, ...,  0.000e+00,  0.000e+00,
         0.000e+00],
       [-1.110e-16,  1.000e+00,  0.000e+00, ...,  0.000e+00, -6.939e-18,
        -3.469e-18],
       [-1.110e-16, -2.220e-16,  1.000e+00, ..., -1.388e-17,  0.000e+00,
         0.000e+00],
       ...,
       [ 3.469e-18,  6.939e-18,  2.776e-17, ...,  1.000e+00,  2.220e-16,
         1.110e-16],
       [ 1.735e-18,  3.469e-18, -3.469e-18, ...,  2.220e-16,  1.000e+00,
         0.000e+00],
       [ 0.000e+00,  0.000e+00, -6.939e-18, ...,  0.000e+00,  0.000e+00,
         1.000e+00]])

In [103]:
error_norm = np.linalg.norm(P-np.eye(P.shape[0]), 'fro')

error_norm

np.float64(1.303919256620991e-13)

In [104]:
tolerance = 1e-12*np.linalg.cond(DD)

if error_norm < tolerance:
    print(f"Stable when n is {size}")
else:
    print(f"Not stable when n is {size}")

Stable when n is 100
