In [334]:
import numpy as np
import heapq

graph = np.array([[0] * 100] * 100)
D = np.array([[0] * 100] * 100)

In [335]:
# n, m = [int(_) for _ in input().split()]
n = 8
m = 10
edges = np.array(
    [
        [1, 2],
        [1, 3],
        [1, 4],
        [2, 4],
        [3, 4],
        [3, 5],
        [5, 7],
        [5, 6],
        [6, 7],
        [6, 8],
    ]
)

for i in range(m):
    # u, v = [int(_) for _ in input().split()]
    u = edges[i][0]
    v = edges[i][1]
    graph[u][v] = 1
    graph[v][u] = 1
    D[u][u] += 1
    D[v][v] += 1

graph = graph[1 : n + 1, 1 : n + 1]
D = D[1 : n + 1, 1 : n + 1]

graph

array([[0, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0]])

In [336]:
D

array([[3, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [337]:
L = D - graph

L

array([[ 3, -1, -1, -1,  0,  0,  0,  0],
       [-1,  2,  0, -1,  0,  0,  0,  0],
       [-1,  0,  3, -1, -1,  0,  0,  0],
       [-1, -1, -1,  3,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  3, -1, -1,  0],
       [ 0,  0,  0,  0, -1,  3, -1, -1],
       [ 0,  0,  0,  0, -1, -1,  2,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  1]])

In [338]:
eigenvalues, eigenvectors = np.linalg.eig(L)

sorted_indices = np.argsort(eigenvalues)
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

eigenvalues

array([-6.89515312e-16,  2.78584797e-01,  1.11161664e+00,  2.31535527e+00,
        3.46643748e+00,  4.00000000e+00,  4.00000000e+00,  4.82800581e+00])

In [339]:
eigenvectors

array([[-0.35355339, -0.36397459,  0.08152079, -0.10132926,  0.27843784,
         0.16545714, -0.75      ,  0.29254334],
       [-0.35355339, -0.42287832,  0.18352616,  0.64263559, -0.37974731,
         0.21151095,  0.08333333, -0.2068902 ],
       [-0.35355339, -0.20367307, -0.11110444, -0.61068087, -0.02856438,
         0.21151095,  0.08333333, -0.62042408],
       [-0.35355339, -0.36397459,  0.08152079, -0.10132926,  0.27843784,
        -0.58847904,  0.58333333,  0.29254334],
       [-0.35355339,  0.1736702 , -0.37284937, -0.21544092, -0.54355219,
         0.21151095,  0.08333333,  0.54905213],
       [-0.35355339,  0.36397459, -0.08152079,  0.10132926, -0.27843784,
        -0.63453285, -0.25      , -0.29254334],
       [-0.35355339,  0.3123272 , -0.5114573 ,  0.36185112,  0.56053534,
         0.21151095,  0.08333333, -0.09070306],
       [-0.35355339,  0.50452858,  0.73036416, -0.07703566,  0.1128907 ,
         0.21151095,  0.08333333,  0.07642187]])

In [340]:
eigenvectors[:, 1]

array([-0.36397459, -0.42287832, -0.20367307, -0.36397459,  0.1736702 ,
        0.36397459,  0.3123272 ,  0.50452858])

In [341]:
[0 if _ < 0 else 1 for _ in eigenvectors[:, 1]]

[0, 0, 0, 0, 1, 1, 1, 1]

In [342]:
graph = np.array([[0] * 100] * 100)

n = 9
m = 13
edges = np.array(
    [
        [1, 2, 1],
        [2, 3, 3],
        [3, 4, 10],
        [1, 7, 6],
        [2, 8, 5],
        [8, 7, 11],
        [8, 6, 7],
        [3, 5, 14],
        [7, 6, 4],
        [6, 5, 2],
        [5, 4, 17],
        [9, 1, 2],
        [9, 7, 9],
    ]
)

for i in range(m):
    u = edges[i][0]
    v = edges[i][1]
    w = edges[i][2]
    graph[u][v] = w

graph[1 : n + 1, 1 : n + 1]

array([[ 0,  1,  0,  0,  0,  0,  6,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  5,  0],
       [ 0,  0,  0, 10, 14,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 17,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  2,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  4,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  7, 11,  0,  0],
       [ 2,  0,  0,  0,  0,  0,  9,  0,  0]])

In [343]:
start = 9
end = 4

q = []
heapq.heappush(q, (0, start))
vis = [False] * (n + 1)
dis = [np.inf] * (n + 1)
dis[start] = 0

while q:
    _, now = heapq.heappop(q)
    if vis[now]:
        continue
    vis[now] = True
    for v in range(1, n + 1):
        if graph[now][v] > 0:
            if dis[now] + graph[now][v] < dis[v]:
                dis[v] = dis[now] + graph[now][v]
                heapq.heappush(q, (dis[v], v))

print(dis[end])

16
